#!/bin/bash
set -e -x -u

om -k --target $OPSMAN_URL --username $OPSMAN_USER --password $OPSMAN_PASSWORD available-products

om -k --target $OPSMAN_URL --username $OPSMAN_USER --password $OPSMAN_PASSWORD stage-product --product-name pivotal-mysql --product-version 2.0.5
