#!/bin/bash
set -e -x -u

# om -k --target https://10.213.10.1 --username admin --password Cloudc0w upload-product --product pivotal-mysql-2.0.5.pivotal

om -k --target $OPSMAN_URL --username $OPSMAN_USER --password $OPSMAN_PASSWORD available-products
