groups:
  - name: om-mysql
    jobs:
      - deploy-product

jobs:
- name: deploy-product
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, crazy world!"]

  #  - get: git
  #    trigger: true

  #  - task: deploy-product
  #    config:
  #      platform: linux
  #      image_resource:
  #        type: docker-image
  #        source:
  #          repository: starkandwayne/concourse
  #          tag:        latest
  #      inputs:
  #        - name: git
  #      run:
  #        path: ./git/om-test-script
  #        args: []

  #resources:
  #- name: git
  #  type: git
  #  source:
  #    uri: https://github.com/givett/om-deploy-product
  #    branch: master
  #    username: ((github_username))
  #    password: ((github_access_token))
