groups:
  - name: om-mysql
    jobs:
      - deploy-product

jobs:
- name: deploy-product
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, crazy world!"]

  - get: git
    trigger: true

  - get: mysql-product
    resource: mysql-product
    trigger: true
    params: { globs: [ pivotal-mysql-2.0.5.pivotal ] }

  - task: deploy-product
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: starkandwayne/concourse
          tag:        latest
      inputs:
        - name: git
      run:
        path: ./git/om-mysql-script
        args: []
      params:
        OPSMAN_URL:      ((opsman_url))
        OPSMAN_USER:     ((opsman_user))
        OPSMAN_PASSWORD: ((opsman_password))

resources:
- name: git
  type: git
  source:
    uri: https://github.com/givett/om-deploy-product
    branch: master
    username: ((github_username))
    password: ((github_access_token))
- name: mysql-product
  type: pivnet
  source:
    api_token:       ((pivnet_token))
    product_slug:    pivotal-mysql
    product_version: 2.0.5

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
